In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import warnings
warnings.filterwarnings("ignore")

In [6]:
titanic = sns.load_dataset('titanic')


titanic1 = titanic
titanic1.head()

def rec_sex (series):
    if series == "female":
        return 1
    if series == "male":
        return 0
    

titanic1['sexR'] = titanic['sex'].apply(rec_sex)


titanic['sex'].value_counts()

titanic1['sexR'].value_counts()

titanic['sex'].isnull()

titanic1['embarked'].value_counts()

titanic1['embarked'].isnull()

def rec_embarked (series):
    if series == "S":
        return 0
    if series == "C":
        return 1
    if series == "Q":
        return 2

titanic1['embarkedR'] = titanic['embarked'].apply(rec_embarked)


titanic1['class'].value_counts()

titanic1['class'].isnull()

def rec_class (series):
    if series == "First":
        return 0
    if series == "Third":
        return 1
    if series == "Second":
        return 2

titanic1['classR'] = titanic['class'].apply(rec_class)


titanic1['who'].value_counts()

titanic1['who'].isnull()

def rec_who (series):
    if series == "man":
        return 0
    if series == "woman":
        return 1
    if series == "child":
        return 2

titanic1['whoR'] = titanic['who'].apply(rec_who)


titanic1['adult_male'].value_counts()


x =titanic1['adult_male'].isnull()

x.value_counts()

def rec_adult_male (series):
    if series == True:
        return 1
    if series == False:
        return 0

titanic1['adult_maleR'] = titanic['adult_male'].apply(rec_adult_male)




titanic1['deck'].value_counts()

titanic1['deck'].isnull()

titanic2 = titanic1.dropna() 

titanic2['deck'].value_counts()


def rec_deck (series):
    if series == "A":
        return 0
    if series == "B":
        return 1
    if series == "A":
        return 2
    if series == "C":
        return 3
    if series == "D":
        return 4
    if series == "E":
        return 5
    if series == "F":
        return 6
    if series == "G":
        return 7
    

titanic2['deckR'] = titanic2['deck'].apply(rec_deck)
titanic2.head()

def rec_alive (series):
    if series == "yes":
        return 1
    if series == "no":
        return 0
    

titanic2['aliveR'] = titanic2['alive'].apply(rec_alive)


def rec_alone (series):
    if series == True:
        return 1
    if series == False:
        return 0
    

titanic2['aloneR'] = titanic2['alone'].apply(rec_alone)


list(titanic2.columns)

titanic2.dtypes

titanic2['age'] = titanic2['age'].astype('int64')

titanic2.dtypes

titanic2['fare'] = titanic2['fare'].astype('int64')
titanic2['embarkedR'] = titanic2['embarkedR'].astype('int64')
titanic2['classR'] = titanic2['classR'].astype('int64')
titanic2['deckR'] = titanic2['deckR'].astype('int64')



titanic2['embark_town'].value_counts()

def rec_embark_town (series):
    if series == 'Southampton':
        return 0
    if series == 'Cherbourg':
        return 1
    if series == 'Queenstown':
        return 2
    

titanic2['embark_townR'] = titanic2['embark_town'].apply(rec_embark_town)


titanic2.dtypes

titanic3 = titanic2[['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare', 'sexR', 'classR', 'embarkedR', 'adult_maleR', 'deckR', 'aloneR', 'embark_townR']]
# Dropped aliveR column as it has 100% correlation.

list(titanic3.columns)

titanic3.head()


#Decision Tree


x = titanic3.drop('survived', axis =1)
y = titanic3['survived']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=76)

decisionTree = DecisionTreeClassifier(random_state=76)
decisionTree.fit(x_train, y_train)

treePredictions = decisionTree.predict(x_test)
print(confusion_matrix(y_test, treePredictions))

print(classification_report(y_test, treePredictions))

#Random Forest

forest = RandomForestClassifier(n_estimators=500, random_state=76)
forest.fit(x_train, y_train)

forestPredictions = forest.predict(x_test)
print(confusion_matrix(y_test, forestPredictions))
print(classification_report(y_test, forestPredictions))



[[12  7]
 [ 9 27]]
              precision    recall  f1-score   support

           0       0.57      0.63      0.60        19
           1       0.79      0.75      0.77        36

    accuracy                           0.71        55
   macro avg       0.68      0.69      0.69        55
weighted avg       0.72      0.71      0.71        55

[[15  4]
 [ 7 29]]
              precision    recall  f1-score   support

           0       0.68      0.79      0.73        19
           1       0.88      0.81      0.84        36

    accuracy                           0.80        55
   macro avg       0.78      0.80      0.79        55
weighted avg       0.81      0.80      0.80        55



In [4]:
#Decision tree algorithm gives 72% accuracy 

In [5]:
#RF algorithm gives 81% accuracy.

In [6]:
feature_importances = pd.Series(forest.feature_importances_, index=x.columns)
feature_importances

pclass          0.017871
age             0.232051
sibsp           0.034926
parch           0.037310
fare            0.219760
sexR            0.109603
classR          0.013325
embarkedR       0.021867
adult_maleR     0.171654
deckR           0.104605
aloneR          0.015994
embark_townR    0.021035
dtype: float64

In [7]:
n_estimators_array = [1, 4, 5, 8, 10, 20, 50, 75, 100, 250, 500]
results = []
for n in n_estimators_array:
    forest = RandomForestClassifier(n_estimators=n, random_state=76)
    forest.fit(x_train, y_train)
    result = accuracy_score(y_test, forest.predict(x_test))
    results.append(result) 
    print(n, ':', result)


1 : 0.6909090909090909
4 : 0.7090909090909091
5 : 0.7818181818181819
8 : 0.8
10 : 0.8363636363636363
20 : 0.8545454545454545
50 : 0.8
75 : 0.7818181818181819
100 : 0.8
250 : 0.8
500 : 0.8


In [8]:

max_features = ['auto', None, 'log2']

max_depth = [10, 20, 30, 40, 50, 60, 70, 80, 90, None]

min_samples_leaf = [1, 2, 4]

random_grid = {'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_leaf': min_samples_leaf}
print(random_grid)


rf = RandomForestClassifier(n_estimators=10)
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 90, cv = 3, random_state=42)
rf_random.fit(x_train, y_train)

{'max_features': ['auto', None, 'log2'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, None], 'min_samples_leaf': [1, 2, 4]}


RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [9]:
rf_random.best_params_

{'min_samples_leaf': 2, 'max_features': None, 'max_depth': 90}

In [13]:
forest = RandomForestClassifier(n_estimators=50, min_samples_leaf=2, max_features="auto", max_depth=90)
forest.fit(x_train, y_train)

forestPredictions = forest.predict(x_test)
print(confusion_matrix(y_test, forestPredictions))
print(classification_report(y_test, forestPredictions))

[[17  2]
 [ 8 28]]
              precision    recall  f1-score   support

           0       0.68      0.89      0.77        19
           1       0.93      0.78      0.85        36

    accuracy                           0.82        55
   macro avg       0.81      0.84      0.81        55
weighted avg       0.85      0.82      0.82        55



In [ ]:
#After tuning our RF give 85% accuracy. 